# Generated by Django 4.2.20 on 2025-05-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuadrante',
            unique_together={('nombre', 'estacion')},
        ),
    ]
